services:
  - type: web
    name: this_is_world_of_tech
    env: node
    branch: main
    repo: https://github.com/TcronebHackx-Md/this_is_world_of_tech.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUDO
        sync: false
